import chromium from '@sparticuz/chromium'
import puppeteer from 'puppeteer-core'

export async function renderPDF(html){
  const browser = await puppeteer.launch({ args: chromium.args, defaultViewport: chromium.defaultViewport, executablePath: await chromium.executablePath(), headless: true })
  const page = await browser.newPage(); await page.setContent(html, { waitUntil: 'networkidle0' })
  const pdf = await page.pdf({ format:'A4', printBackground:true }); await browser.close(); return pdf
}
export function idCardHTML(m){ const site=process.env.NEXT_PUBLIC_SITE_URL||''; const logo=`${site}/assets/logo.png`; const qr=`${site}/api/qr?token=${m.qr_token||''}`; return `<!doctype html><html><head><meta charset='utf-8'/><style>body{font-family:system-ui;margin:0}.card{width:860px;height:540px;padding:24px;border:4px solid #2563eb;border-radius:16px;position:relative}.row{display:flex;justify-content:space-between;align-items:flex-start}.qr{width:140px;height:140px}.logo{height:56px}.title{color:#2563eb;font-weight:800;letter-spacing:.06em}</style></head><body><div class='card'><div class='row'><div style='display:flex;gap:12px;align-items:center'><img class='logo' src='${logo}'/><div><div class='title'>NORTH INDIA SELF DEFENSE FEDERATION</div><h2 style='margin:6px 0 0 0'>Membership ID Card</h2></div></div><img class='qr' src='${qr}'/></div><div style='margin-top:12px'><p><b>Name:</b> ${m.full_name}</p><p><b>Member No:</b> ${m.member_no}</p><p><b>Type:</b> ${m.type_label || m.type_id}</p><p><b>Year:</b> ${(new Date()).getFullYear()}</p></div></div></body></html>` }
export function certificateHTML(m){ const site=process.env.NEXT_PUBLIC_SITE_URL||''; const logo=`${site}/assets/logo.png`; const seal=`${site}/assets/seal.jpg`; const sign=`${site}/assets/sign.jpg`; const qr=`${site}/api/qr?token=${m.qr_token||''}`; return `<!doctype html><html><head><meta charset='utf-8'/><style>body{font-family:system-ui;margin:0}.wrap{width:900px;height:640px;padding:40px;border:8px double #0ea5e9;position:relative}h1{text-align:center;color:#0ea5e9;margin:6px 0 10px 0}.qr{width:120px;height:120px;position:absolute;right:40px;bottom:40px}.seal{width:120px;position:absolute;left:40px;bottom:36px;opacity:0.9}.sign{width:160px;position:absolute;right:200px;bottom:80px}.header{display:flex;align-items:center;gap:12px}.logo{height:64px}.meta{margin-top:8px}</style></head><body><div class='wrap'><div class='header'><img class='logo' src='${logo}'/><div><div style='font-weight:800;letter-spacing:.04em'>NORTH INDIA SELF DEFENSE FEDERATION</div><div>Meerut, Uttar Pradesh</div></div></div><h1>Certificate of Membership</h1><p>This certifies that <b>${m.full_name}</b> (Member No <b>${m.member_no}</b>) is an approved member of the North India Self Defense Federation.</p><div class='meta'><p>Date: ${(new Date()).toLocaleDateString()}</p></div><img class='seal' src='${seal}'/><img class='sign' src='${sign}'/><img class='qr' src='${qr}'/><div style='position:absolute;right:180px;bottom:48px;text-align:center;font-size:12px'><div style='border-top:1px solid #444;margin-top:6px'>Director</div></div></div></body></html>` }
export function donationReceiptHTML(d){ const site=process.env.NEXT_PUBLIC_SITE_URL||''; const logo=`${site}/assets/logo.png`; return `<!doctype html><html><head><meta charset='utf-8'/><style>body{font-family:system-ui;margin:0;padding:32px}header{display:flex;align-items:center;gap:12px;border-bottom:2px solid #0ea5e9;margin-bottom:12px;padding-bottom:8px}.logo{height:48px}h1{color:#0ea5e9}</style></head><body><header><img class='logo' src='${logo}'/><div><h2>NORTH INDIA SELF DEFENSE FEDERATION</h2><div>Donation Receipt</div></div></header><h1>Receipt</h1><p><b>Name:</b> ${d.donor_name||''}</p><p><b>Amount:</b> ₹${d.amount}</p><p><b>Txn ID:</b> ${d.txn_id||d.payment_id||''}</p><p><b>Date:</b> ${(new Date()).toLocaleString()}</p><p>Thank you for supporting our mission.</p></body></html>` }
